"""add trigger to authors_book

Revision ID: 00fbaa7ebb3b
Revises: b968bd354189
Create Date: 2024-12-17 21:35:50.189353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.project.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '00fbaa7ebb3b'
down_revision: Union[str, None] = 'b968bd354189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
    CREATE OR REPLACE FUNCTION update_view_book()
    RETURNS TRIGGER AS $$
    BEGIN
        REFRESH MATERIALIZED VIEW {settings.POSTGRES_SCHEMA}.view_book;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute(f"""
    CREATE OR REPLACE TRIGGER trigger_authors_book
    AFTER DELETE OR INSERT ON {settings.POSTGRES_SCHEMA}.authors_book
    FOR EACH ROW
    EXECUTE FUNCTION update_view_book();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
