"""Unique INN in publisher table

Revision ID: 291f6fe7f3f4
Revises: 3d8ecddda7e7
Create Date: 2024-11-13 21:36:09.087560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291f6fe7f3f4'
down_revision: Union[str, None] = '3d8ecddda7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'birthday',
               existing_type=sa.DATE(),
               nullable=True,
               schema='my_app_schema')
    op.create_unique_constraint(None, 'publishers', ['inn'], schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publishers', schema='my_app_schema', type_='unique')
    op.alter_column('authors', 'birthday',
               existing_type=sa.DATE(),
               nullable=False,
               schema='my_app_schema')
    # ### end Alembic commands ###
