"""add url to genres

Revision ID: 479ff2deaa8f
Revises: fd394ec2d8ae
Create Date: 2024-12-23 16:25:33.786343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479ff2deaa8f'
down_revision: Union[str, None] = 'fd394ec2d8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('url', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False), schema='my_app_schema')
    op.create_unique_constraint(None, 'genres', ['url'], schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', schema='my_app_schema', type_='unique')
    op.drop_column('genres', 'url', schema='my_app_schema')
    # ### end Alembic commands ###
