"""add admin

Revision ID: 51d24d14e27f
Revises: 7113170b55c0
Create Date: 2024-12-10 19:58:03.168636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.project.api.authorization.hash import get_password_hash

# revision identifiers, used by Alembic.
revision: str = '51d24d14e27f'
down_revision: Union[str, None] = '7113170b55c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"INSERT INTO my_app_schema.readers "
               f"VALUES (default, 'admin', 'admin', '+79999999999', '10-12-2024', '{get_password_hash('admin')}', 'ADMIN')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DELETE FROM readers WHERE name = 'admin'")
    # ### end Alembic commands ###
