"""add role

Revision ID: 7113170b55c0
Revises: e93fab54ebcd
Create Date: 2024-12-10 12:51:23.621722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.project.core.config import settings
from src.project.core.enums.Role import Role

# revision identifiers, used by Alembic.
revision: str = '7113170b55c0'
down_revision: Union[str, None] = 'e93fab54ebcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM ('USER', 'ADMIN')")
    op.add_column('readers', sa.Column('role', sa.Enum('USER', 'ADMIN', name='role')), schema=settings.POSTGRES_SCHEMA)
    op.execute(f"UPDATE my_app_schema.readers SET role = 'USER'")
    op.alter_column('readers','role', nullable=False, schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readers', 'role', schema=settings.POSTGRES_SCHEMA)
    op.execute("DROP TYPE IF EXISTS role")
    # ### end Alembic commands ###
