"""add supply view

Revision ID: 8c521a3847f0
Revises: 479ff2deaa8f
Create Date: 2024-12-25 16:34:14.967744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.project.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '8c521a3847f0'
down_revision: Union[str, None] = '479ff2deaa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

''''
id_instance, id_book, book_name, publisher_name, id_author, author_name, supply_date
'''
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
        CREATE VIEW {settings.POSTGRES_SCHEMA}.supply_view AS
        SELECT
            book_instance.id_instance as id_instance,
            books.id_book as id_book,
            books.name as book_name,
            publishers.name as publisher_name,
            authors.id_author as id_author,
            authors.name as author_name,
            book_instance.supply_date as supply_date
        FROM {settings.POSTGRES_SCHEMA}.book_instance
        JOIN {settings.POSTGRES_SCHEMA}.book_publisher ON book_publisher.id_book_publisher = book_instance.id_book_publisher
        JOIN {settings.POSTGRES_SCHEMA}.publishers ON publishers.id_publisher = book_publisher.id_publisher
        JOIN {settings.POSTGRES_SCHEMA}.books ON books.id_book = book_publisher.id_book
        JOIN {settings.POSTGRES_SCHEMA}.authors_book ON authors_book.id_book = books.id_book
        JOIN {settings.POSTGRES_SCHEMA}.authors ON authors.id_author = authors_book.id_author;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
    DROP VIEW {settings.POSTGRES_SCHEMA}.supply_view;
    """)
    # ### end Alembic commands ###
