"""add penalty view

Revision ID: af774006a0a3
Revises: f0e7dbc81a81
Create Date: 2024-12-25 21:35:21.608741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.project.core.config import settings

# revision identifiers, used by Alembic.
revision: str = 'af774006a0a3'
down_revision: Union[str, None] = 'f0e7dbc81a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
        CREATE VIEW {settings.POSTGRES_SCHEMA}.penalty_view AS
        SELECT
            readers.reader_ticket as reader_ticket,
            readers.name as reader_name,
            readers.email as reader_email,
            book_reader.id_instance as id_instance,
            book_reader.id_book_reader as id_book_reader,
            books.id_book as id_book,
            books.name as book_name,
            publishers.name as publisher_name,
            penalty.start_time as start_time,
            penalty.payment as payment
        FROM {settings.POSTGRES_SCHEMA}.penalty
        JOIN {settings.POSTGRES_SCHEMA}.book_reader ON book_reader.id_book_reader = penalty.id_book_reader
        JOIN {settings.POSTGRES_SCHEMA}.readers ON readers.reader_ticket = book_reader.reader_ticket
        JOIN {settings.POSTGRES_SCHEMA}.book_instance ON book_instance.id_instance = book_reader.id_instance
        JOIN {settings.POSTGRES_SCHEMA}.book_publisher ON book_publisher.id_book_publisher = book_instance.id_book_publisher
        JOIN {settings.POSTGRES_SCHEMA}.publishers ON publishers.id_publisher = book_publisher.id_publisher
        JOIN {settings.POSTGRES_SCHEMA}.books ON books.id_book = book_publisher.id_book;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
    DROP VIEW {settings.POSTGRES_SCHEMA}.penalty_view;
    """)
    # ### end Alembic commands ###
