"""add views

Revision ID: b968bd354189
Revises: 51d24d14e27f
Create Date: 2024-12-17 19:17:01.376931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.project.core.config import settings


# revision identifiers, used by Alembic.
revision: str = 'b968bd354189'
down_revision: Union[str, None] = '51d24d14e27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
    CREATE MATERIALIZED VIEW {settings.POSTGRES_SCHEMA}.view_book AS
    SELECT 
        books.name as book_name, 
        authors.name as author_name, 
        books.year as book_year,
        books.id_book as id_book,
        authors.id_author as id_author,
        authors_book.id_authors_book as id_authors_book
    FROM {settings.POSTGRES_SCHEMA}.authors_book 
    JOIN {settings.POSTGRES_SCHEMA}.authors ON authors_book.id_author = authors.id_author
    JOIN {settings.POSTGRES_SCHEMA}.books ON authors_book.id_book = books.id_book;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP MATERIALIZED VIEW {settings.POSTGRES_SCHEMA}.view_book")
    # ### end Alembic commands ###
