"""add order view

Revision ID: f0e7dbc81a81
Revises: 8c521a3847f0
Create Date: 2024-12-25 19:14:15.586140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.project.core.config import settings

# revision identifiers, used by Alembic.
revision: str = 'f0e7dbc81a81'
down_revision: Union[str, None] = '8c521a3847f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

'''
    id_book_reader, reader_ticket, reader_name, reader_email, id_instance, id_book,
    book_name, publisher_name, borrow_date, end_date
'''
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
        CREATE VIEW {settings.POSTGRES_SCHEMA}.order_view AS
        SELECT
            book_reader.id_book_reader as id_book_reader,
            book_reader.reader_ticket as reader_ticket,
            readers.name as reader_name,
            readers.email as reader_email,
            book_reader.id_instance as id_instance,
            books.id_book as id_book,
            books.name as book_name,
            publishers.name as publisher_name,
            book_reader.borrow_date as borrow_date,
            book_reader.end_date as end_date
        FROM {settings.POSTGRES_SCHEMA}.book_reader
        JOIN {settings.POSTGRES_SCHEMA}.readers ON readers.reader_ticket = book_reader.reader_ticket
        JOIN {settings.POSTGRES_SCHEMA}.book_instance ON book_instance.id_instance = book_reader.id_instance
        JOIN {settings.POSTGRES_SCHEMA}.book_publisher ON book_publisher.id_book_publisher = book_instance.id_book_publisher
        JOIN {settings.POSTGRES_SCHEMA}.publishers ON publishers.id_publisher = book_publisher.id_publisher
        JOIN {settings.POSTGRES_SCHEMA}.books ON books.id_book = book_publisher.id_book;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
    DROP VIEW {settings.POSTGRES_SCHEMA}.order_view;
    """)
    # ### end Alembic commands ###
